Added models for hotel loader
happy-travel/fastpayhotels-connector pull request #21
Opened 2022-08-10 09:48 UTC by PKorovinPromo-Z

2022-08-11 12:25 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Constants.cs
> +    public static readonly string[] Languages = new[] { "ar", "en", "ru", "bg", "de", "el", "es", "fr", "it", "hu", "pl", "pt", "ro", "sr", "tr" };
Can't we use ISO codes here? like CultureInfo.TwoLetterISOLanguageName

2022-08-11 12:28 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Catalogue/Caption.cs
> +    public string Lang { get; set; }
Better to use Culture

2022-08-11 12:29 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Catalogue/CatalogueRequest.cs
> +    /// List of languages in which the information is requested, use culture ids based on ISO 639-1, this filter is optional. If languages is null or empty by default system return "English".
Same here

2022-08-11 12:31 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/DataObject.cs
> +public class DataObject
Too wide name, maybe FastPayObject or something like this?

2022-08-11 12:32 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Hotel/Description.cs
> +    public string Language { get; set; }
Same for language here

2022-08-11 12:32 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Hotel/HotelDetails.cs
> +    public string TimeZone { get; set; }
Time zone string?

2022-08-11 12:33 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Hotel/HotelDetails.cs
> +    public List<object> Tags { get; set; }
Is it really object? No type?

2022-08-11 12:35 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Hotel/Image.cs
> +    /// Default image name in Fastpayhotels' system.
image name? not a url or something?

2022-08-11 12:36 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Hotel/Image.cs
> +    public string Url { get; set; }
So if we have url than we do we need name of the image?

2022-08-11 12:36 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Hotel/Image.cs
> +    public string Url { get; set; }
and its better to use Uri for Urls

2022-08-11 12:37 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/Models/HotelListRequest.cs
> +        FromLastUpdateDate = fromLastUpdateDate.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz", CultureInfo.InvariantCulture);
TO constants

2022-08-11 12:38 UTC, suhan3z requested changes
According to comments

2022-08-11 14:02 UTC, PKorovinPromo-Z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Hotel/HotelDetails.cs
> +    public string TimeZone { get; set; }
Yes, the supplier returns the time zone as a string. Example: Romance Standard Time.

2022-08-19 10:14 UTC, suhan3z approved these changes

2022-08-19 10:16 UTC, merged