Accommodation updating implemented
happy-travel/fastpayhotels-connector pull request #23
Opened 2022-09-05 09:41 UTC by PKorovinPromo-Z

2022-09-05 09:43 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Catalogue/CatalogueType.cs
> +public class CatalogueType : RootType
Lack of comments

2022-09-05 09:44 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Catalogue/ServiceType.cs
> +public class ServiceType : CatalogueType
Lack of comments

2022-09-05 09:44 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/Catalogue/TuristicAreaType.cs
> +public class TuristicAreaType : CatalogueType
Lack of comments

2022-09-05 09:44 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/RootType.cs
> +public class RootType
Lack of comments

2022-09-05 09:46 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Service/TokenAuthHeader/TokenAuthHeaderClient.cs
> +                var responseError = JsonSerializer.Deserialize<TokenErrorMessage>(content);
We have many error codes, why it can be only Token Error?

2022-09-05 09:48 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/Infrastructure/DateTimeProvider.cs
> +    public DateTimeOffset UtcNow() => DateTimeOffset.UtcNow;
What's it for?

2022-09-05 09:49 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/Models/HotelSummary.cs
> +public class HotelSummary
Lack of comment

2022-09-05 09:50 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/Service/AccommodationManager.cs
> +                updatedAccommodation.Name = accommodation.Name;
Extract it to a service method

2022-09-05 09:51 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/Service/AccommodationManager.cs
> +        bool IsAccommodationChanged(Accommodation oldAccommodation, Accommodation newAccommodation)
We already told that it should be in Accommodation class

2022-09-05 09:52 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/Service/AccommodationManager.cs
> +    /// Get the hotel list by quota from the hotel list response
Extend description about qouta

2022-09-05 09:53 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/Service/UpdateHistoryService.cs
> +    public async Task<int> Create(RawDataUpdateOptions options)
Lack of comments

2022-09-05 09:54 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/Service/UpdateHistoryService.cs
> +    public async Task<DateTimeOffset?> GetLastSuccessfulUpdateTime()
Same here

2022-09-05 09:55 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/Settings/UpdateMode.cs
> +public enum UpdateMode
Comments

2022-09-05 09:56 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/StaticDataUpdateHostedService.cs
> +                await worker.Run(stoppingToken);
What is the timeout for worker?

2022-09-05 09:57 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/Workers/IUpdateWorker.cs
> +public interface IUpdateWorker
Comment

2022-09-05 09:58 UTC, suhan3z requested changes
According to comments

2022-09-05 10:53 UTC, PKorovinPromo-Z commented on HappyTravel.FastpayhotelsConnector.Common/Service/TokenAuthHeader/TokenAuthHeaderClient.cs
> +                var responseError = JsonSerializer.Deserialize<TokenErrorMessage>(content);
Because this service is only used to get the token.

2022-09-05 11:50 UTC, PKorovinPromo-Z commented on HappyTravel.FastpayhotelsConnector.Updater/StaticDataUpdateHostedService.cs
> +                await worker.Run(stoppingToken);
I do not know this. Made similarly to other connectors.

2022-09-05 15:13 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/Service/AccommodationManager.cs
> +                updatedAccommodation.Name = accommodation.Name;
And what did you resolve?

2022-09-05 15:16 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Updater/StaticDataUpdateHostedService.cs
> +                await worker.Run(stoppingToken);
If your updater will hang somehow, operation won't stop until the pod shutdown, that's why you need to specify timeout

2022-09-06 05:33 UTC, PKorovinPromo-Z commented on HappyTravel.FastpayhotelsConnector.Updater/Workers/AccommodationUpdater.cs
> +        return errorMessage.Contains(quotaExceededMessage);
This message is generated by me in FastpayhotelsContentClient and does not come from the supplier. Therefore, why ignore the case?

2022-09-09 08:39 UTC, DaniyarAskarov commented on HappyTravel.FastpayhotelsConnector.Common/Service/TokenAuthHeader/TokenAuthHeaderClient.cs
> +            errorMessage = "Get an Agency rol acces token request failed";
Role access?

2022-09-09 08:39 UTC, DaniyarAskarov commented on HappyTravel.FastpayhotelsConnector.Common/Service/TokenAuthHeader/TokenAuthHeaderClient.cs
> +            _logger.LogGetAgencyRolTokenRequestFailed(ex, errorMessage);
AgencyRole?

2022-09-09 08:39 UTC, DaniyarAskarov commented on HappyTravel.FastpayhotelsConnector.Updater/Service/AccommodationManager.cs
> +    public async Task SaveChanges()
You could pass cancellationToken to this method as well

2022-09-09 08:39 UTC, DaniyarAskarov commented on HappyTravel.FastpayhotelsConnector.Updater/Service/UpdateHistoryService.cs
> +    public async Task<int> Create(RawDataUpdateOptions options)
Also could pass cancellationToken to this method

2022-09-09 08:39 UTC, DaniyarAskarov commented on HappyTravel.FastpayhotelsConnector.Updater/Service/UpdateHistoryService.cs
> +    public async Task<DateTimeOffset?> GetLastSuccessfulUpdateTime()
Also could pass cancellationToken to here and methods below

2022-09-12 06:41 UTC, DaniyarAskarov approved these changes

2022-09-12 06:49 UTC, merged