Refactored token handler (#8)
happy-travel/fastpayhotels-connector pull request #9
Opened 2022-06-22 05:45 UTC by PKorovinPromo-Z

* Api project added to solution

* Added ServiceCollectionExtensions

* Refactored TokenAuthHeaderHandler

* Fixed variable name

2022-08-01 11:48 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Constants.cs
> +    public static readonly TimeSpan AuthTokenLifeTime = TimeSpan.FromDays(400); // The access token has a validity of 400 days
It's better to have a measurement scale in the name. AuthTokenLifeTimeDays for example

2022-08-01 11:49 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +        public static IServiceCollection AddTokenAuthHeaderService(this IServiceCollection services, string tokenEndPoint)
You still challenging me by lack of comments. but i strong ;)

2022-08-01 11:49 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +                var jitter = new Random();
What is jitter?

2022-08-01 11:49 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +                .SetHandlerLifetime(TimeSpan.FromMinutes(5))
to const

2022-08-01 11:50 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +                    .WaitAndRetryAsync(3, attempt
Too much magic numbers

2022-08-01 11:50 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +                        => TimeSpan.FromSeconds(Math.Pow(1.5, attempt)) + TimeSpan.FromMilliseconds(jitter.Next(0, 100)));
here too

2022-08-01 11:50 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Infrastructure/Options/ApiConnection.cs
> +    public string AvailabilityEndPoint { get; set; }
Comments

2022-08-01 11:51 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Models/TokenErrorMessage.cs
> +    public string Error { get; set; }
Comments

2022-08-01 11:51 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Service/TokenAuthHeader/TokenAuthHeaderClient.cs
> +    public async Task<Result<string>> GetAgencyRolToken(CancellationToken cancellationToken)
Comments

2022-08-01 11:51 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Service/TokenAuthHeader/TokenAuthHeaderClient.cs
> +        var content = new FormUrlEncodedContent(new List<KeyValuePair<string, string>>()
Maybe extract to service method?

2022-08-01 11:53 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Service/TokenAuthHeader/TokenAuthHeaderService.cs
> +    public async Task<Result<string>> GetOrSetToken(CancellationToken cancellationToken)
Very confusing method name and logic

2022-08-01 11:54 UTC, suhan3z commented on HappyTravel.FastpayhotelsConnector.Common/Service/TokenAuthHeader/TokenAuthHeaderStorage.cs
> +public class TokenAuthHeaderStorage
Comments

2022-08-01 11:55 UTC, suhan3z requested changes
According to comments

2022-08-01 12:48 UTC, PKorovinPromo-Z commented on HappyTravel.FastpayhotelsConnector.Common/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +                var jitter = new Random();
Taken from edo: https://github.com/happy-travel/edo/blob/469ce388215e0ddcc4cd07e23338d9911071b8ec/Api/Infrastructure/ServiceCollectionExtensions.cs#L824

2022-08-05 12:59 UTC, suhan3z approved these changes

2022-08-05 13:02 UTC, merged